# Site Meta
title:            Balaji Developers
tagline:          Building Elegant Homes
description:      We develop beautifully designed and affordable new homes in the finest locations that are built with unmatched efficiencies and uncompromising quality.

domain:           balajivgtm.com
type:             website
logo:             /logo.png

contact:  contact@codemons.com
contact-encoded: '&#099;&#111;&#110;&#116;&#097;&#099;&#116;&#064;&#099;&#111;&#100;&#101;&#109;&#111;&#110;&#115;&#046;&#099;&#111;&#109;'

#Assets paths
css: /assets/css
js: /assets/js
img: /assets/img
font: /assets/font

baseurl:          ''

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://codemons.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: rouge
permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v1.1.0


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
